baseURL: "https://hyeomans.com/"
title: Hector Yeomans
pagination:
  pagerSize: 5
theme: [ "hugo-chart", "PaperMod" ]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
canonifyURLs: true
relativeURLs: true

outputs:
  home:
  - HTML
  - RSS
  - JSON # is necessary

googleAnalytics: "G-CQCQ4X7JHE"

minify:
  disableXML: true
  # minifyOutput: true

  # Suppress warnings
ignoreLogs:
- 'warning-goldmark-raw-html'

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      tag: tags
      series: series
      category: categories
    menu:
      main:
      - name: Services
        url: services/
        weight: 1
      - name: Posts
        url: posts/
        weight: 3
      - name: Tags
        url: tags/
        weight: 5
      - name: Series
        url: series/
        weight: 7
      - name: Search
        url: search/
        weight: 10
  es:
    params:
      languageName: ":es:"
      languageAltTitle: Espanol
      weight: 2
      title: OpenTech
      homeInfoParams:
        title: "OpenTech"
        Content: "OpenTech, un blog escrito por Héctor Yeomans, es un recorrido analítico por la convergencia entre tecnología, datos abiertos, solicitudes de transparencia y gobierno abierto."
      taxonomies:
        tag: Tags
        series: Series
        category: Categories
    menu:
      main:
      - name: Servicios
        url: services/
        weight: 1
      - name: Posts
        url: posts/
        weight: 3
      - name: Tags
        url: tags/
        weight: 5
      - name: Series
        url: series/
        weight: 7
      - name: Busqueda
        url: busqueda/
        weight: 10

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: OpenTech
  description: "OpenTech, un blog escrito por Héctor Yeomans, es un recorrido analítico por la convergencia entre tecnología, datos abiertos, solicitudes de transparencia y gobierno abierto."
  keywords: [ Blog, Technology, Open Data, Government Transparency, Software Development, Go, JavaScript, Microservices ]
  author: "Hector Yeomans"
  # author: ["Me", "You"] # multiple authors
  images: [ "/img/lupa.jpg" ]
  DateFormat: "January 2, 2006"

  # SEO improvements
  enableRobotsTXT: true
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true # Enable next/prev navigation
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true # Show word count for better UX
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true # Use Hugo's built-in TOC
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
    - name: Posts
      url: posts
    - name: Tags
      url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there 👋"
    Content: "I'm Hector Yeomans, a software engineer and consultant specializing in Go development, government transparency, and workflow automation. I help businesses build scalable applications, navigate Mexican transparency laws (LGT), and streamline operations with N8N automation. [Explore my services →](/services/)"

  socialIcons:
  - name: twitter
    url: "https://twitter.com/h_yeomans"
  - name: github
    url: "https://github.com/hyeomans"
  - name: linkedin
    url: "https://www.linkedin.com/in/hector-yeomans"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # show on individual post pages

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]
menu:
  main:
  - identifier: categories
    name: categories
    url: /categories/
    weight: 10
  - identifier: tags
    name: tags
    url: /tags/
    weight: 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
